# Generated by Django 3.0.7 on 2020-06-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='about2',
            field=models.TextField(default='-'),
        ),
    ]
