# Generated by Django 3.0.7 on 2020-06-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_main_about2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='about',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='main',
            name='about2',
            field=models.TextField(),
        ),
    ]
