# Generated by Django 3.0.7 on 2020-06-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200611_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='fb',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='main',
            name='ig',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='main',
            name='tw',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='main',
            name='yt',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='main',
            name='about',
            field=models.TextField(max_length=450),
        ),
        migrations.AlterField(
            model_name='main',
            name='about2',
            field=models.TextField(max_length=450),
        ),
    ]
